# source '/blah/blah/zshrc'


# ===== Aliases ===== #

alias rootmount='echo mount\ -o\ remount,rw\ 0\ /'
alias installrpm='rpm -ivh'
alias installtar='tar -zxvf'
alias sshserv='sudo rcsshd restart'
alias cycleplasma='kquitapp5 plasmashell && kstart plasmashell'
alias color256='for code ({000..255}) print -P -- "$code: %F{$code}\u2588\u2588\u2588\u2588 These are colors!%f"'
alias vcs='vcson'

alias o="xdg-open"
alias ll='ls -l'
alias lla='ls -lA'
alias swd='pwd > ~/Scripts/shell/wd'
alias lwd='dir=$(cat ~/Scripts/shell/wd); cd $dir'
alias clip='xsel -ib'

alias capsoff="setxkbmap -layout us -option caps:escape"
alias capson="setxkbmap -layout us -option"

# Dev tools
alias a='tmux a -t'
alias tp='tmuxp load tmuxp'
alias git='git '
alias logg='log --graph --decorate --all'
alias vi='vim'
alias dgo='python manage.py'


# ===== Functions ===== #

function proc() {
  ps aux | grep $1 --color=always | grep -v "grep.\+$1"
}

function md() {
  mkdir -p "$@" && cd "$1";
}

function arename() {
  echo -ne "\033]30;$1\007"
  tmux a -t $1
  echo -ne "\033]30;$(pwd|rev|cut -d / -f1|rev) : zsh\007"
}

function rename() {
  echo -ne "\033]30;$1\007"
}

function unname() {
  echo -ne "\033]30;$(pwd|rev|cut -d / -f1|rev) : zsh\007"
}

function vcsoff() {
  POWERLEVEL9K_LEFT_PROMPT_ELEMENTS_BACKUP=("${POWERLEVEL9K_LEFT_PROMPT_ELEMENTS[@]}")
  POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=($(echo $POWERLEVEL9K_LEFT_PROMPT_ELEMENTS | sed -r 's/(\s|^)vcs(\s|$)/ /'))
}

function vcson() {
  if [[ "$POWERLEVEL9K_LEFT_PROMPT_ELEMENTS_BACKUP" != ""  ]]; then
    POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=("${POWERLEVEL9K_LEFT_PROMPT_ELEMENTS_BACKUP[@]}")
  fi
}

function vim-plug() {
  mkdir -p ~/.vim/autoload
  curl --insecure -fLo ~/.vim/autoload/plug.vim \
    https://raw.github.com/junegunn/vim-plug/master/plug.vim
}

function gitnotify() {
  inotifywait -m -r -e modify -e create -e close_write -e attrib .git/ | while read ; do
    clear
    git --no-pager log --graph --decorate --color | head -n $((`tput lines`-2))
  done
}

# ===== Plugins ===== #

# autocomplete
plugins=(zsh-completions)
autoload -U compinit && compinit

# pure prompt
unset CONDA_DEFAULT_ENV
autoload -U promptinit; promptinit
prompt pure

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# ===== Other Crap ===== #


# Set environment variables
export TERM="xterm-256color"
if [ -z $POWERLINE ];then
  export POWERLINE=1
fi
if [ -z $VCS_OFF ];then
  export VCS_OFF=0
fi

eval "$(dircolors -b)"

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# colorize outputs
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=always'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'
    alias grep='grep --color=always'
    alias fgrep='fgrep --color=always'
    alias egrep='egrep --color=always'
fi

# History settings
setopt HIST_IGNORE_DUPS
HISTFILE=~/.zsh_history
SAVEHIST=1000

# Improved X11 forwarding through GNU Screen (or tmux).
#   If not in screen or tmux, update the DISPLAY cache.
#   If we are, update the value of DISPLAY to be that in the cache.
function update-x11-forwarding
{
    if [ -z "$STY" -a -z "$TMUX" ]; then
        echo $DISPLAY > ~/.display
    else
        export DISPLAY=`cat ~/.display`
    fi
}
# This is run before every command.
preexec() {
    # Don't cause a preexec for PROMPT_COMMAND.
    # Beware!  This fails if PROMPT_COMMAND is a string containing more than one command.
    #[ "$BASH_COMMAND" = "$PROMPT_COMMAND" ] && return
    update-x11-forwarding
    # Debugging.
    #echo DISPLAY = $DISPLAY, display file = `cat ~/.display`, STY = $STY, TMUX = $TMUX
}
#trap 'preexec' DEBUG

# Move into symdirs
for key val in ${(kv)SYMDIRS}; do
  if [[ $PWD == $key* ]]; then
    cd $val${PWD:${#key}}
    break
  fi
done
# Example assoc array for private zshrc
# typeset -A SYMDIRS
# SYMDIRS[/mnt/Data/Dropbox]='/home/matthew/Dropbox'

# Turn vcs off in new shells if tmux
if [ "$TMUX_PWD" = "$PWD" ]; then
  VCS_OFF=1
fi

# Turn vcs on/off when changing dirs in tmux
chpwd() {
  if [ "$TMUX_PWD" = "$PWD" ]; then
    vcsoff
  else
    vcson
  fi
}

# Pretty picture startup
if [ "${"$(env|grep KONSOLE_DBUS_SESSION)": -1}" = "1" ] && [ "$TMUX" = "" ]; then
  command -v neofetch > /dev/null && neofetch
fi
